{% set name = "clawpack" %}
{% set version = "5.11.0" %}

{% set mpi = mpi %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 63f9e26a6ed630ad485419fbe3825280b176627db266121ce2f6f57bb53898e7
  patches:
    - patches/64.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ mpi }}                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - pip
    - python
    - setuptools <61
    - numpy
    - six
    - {{ mpi }}
  run:
    - {{ mpi }}
    - h5py * mpi_{{ mpi }}_*
    - python
    - six
    - numpy
    - scipy
    - matplotlib-base
    - mpi4py
    - petsc4py

test:
  imports:
    - clawpack.pyclaw
    - clawpack.petclaw
    - clawpack.pyclaw.fileio.hdf5
    - clawpack.riemann.euler_4wave_2D
  requires:
    - pip
  commands:
    - pip check
    - python -c "from clawpack.pyclaw import examples; claw = examples.shock_bubble_interaction.setup(); claw.run()"


about:
  home: https://github.com/clawpack/clawpack
  summary: Package for solving hyperbolic systems of partial differential equations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
